/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.tagbalay.views;

import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author BlackHat
 */
@StyleSheet
@Template(CrudFormPage.class)
public class MasterElectoraltermPage extends javax.swing.JPanel {

    /**
     * Creates new form MasterElectoralterm
     */
    public MasterElectoraltermPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xHorizontalPanel2 = new com.rameses.rcp.control.XHorizontalPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xDateField2 = new com.rameses.rcp.control.XDateField();

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("Electoral Term");
        xHorizontalPanel2.setBorder(xTitledBorder1);
        com.rameses.rcp.control.layout.HorizontalLayout horizontalLayout3 = new com.rameses.rcp.control.layout.HorizontalLayout();
        xHorizontalPanel2.setLayout(horizontalLayout3);

        xTextField1.setCaption("Description");
        xTextField1.setCaptionWidth(100);
        xTextField1.setName("entity.description"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField1.setVisibleWhen("");
        xFormPanel1.add(xTextField1);

        xDateField1.setText("entity.termbeginning");
        xDateField1.setCaption("Term beginning");
        xDateField1.setCaptionWidth(100);
        xDateField1.setName("entity.termbeginning"); // NOI18N
        xDateField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xDateField1);

        xDateField2.setCaption("Term end");
        xDateField2.setCaptionWidth(100);
        xDateField2.setName("entity.termend"); // NOI18N
        xDateField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xDateField2);

        xHorizontalPanel2.add(xFormPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xHorizontalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xHorizontalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XHorizontalPanel xHorizontalPanel2;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
