/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.tagbalay.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author rufino
 */
@Template({FormPage.class})
@StyleSheet
public class TagBalayGeneralInfoSectionTemplate extends javax.swing.JPanel {

    /**
     * Creates new form ConfirmPage
     */
    public TagBalayGeneralInfoSectionTemplate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xHorizontalPanel1 = new com.rameses.rcp.control.XHorizontalPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("General Information");
        xHorizontalPanel1.setBorder(xTitledBorder1);
        xHorizontalPanel1.setBorderSeparator(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xHorizontalPanel1.setPreferredSize(new java.awt.Dimension(1008, 149));

        xFormPanel1.setCaptionWidth(150);
        xFormPanel1.setName(""); // NOI18N
        xFormPanel1.setPreferredSize(new java.awt.Dimension(500, 100));

        xLabel1.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel1.setCaption("HIN");
        xLabel1.setExpression("#{entity.hin}");
        xLabel1.setOpaque(true);
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel1.add(xLabel1);

        xLabel2.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel2.setCaption("Pangulo sa Pamilya");
        xLabel2.setExpression("#{entity.tagbalay.pangulo.name}");
        xLabel2.setOpaque(true);
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 16));
        xFormPanel1.add(xLabel2);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 63));

        xTextArea1.setEditable(false);
        xTextArea1.setText("entity.tagbalay.address.text");
        xTextArea1.setCaption("Nahimutangan sa Panimalay");
        xTextArea1.setName("entity.tagbalay.address.text"); // NOI18N
        jScrollPane1.setViewportView(xTextArea1);

        xFormPanel1.add(jScrollPane1);

        xHorizontalPanel1.add(xFormPanel1);

        xFormPanel2.setCaptionWidth(130);
        xFormPanel2.setPreferredSize(new java.awt.Dimension(500, 100));

        xLabel6.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel6.setCaption("Klase sa survey");
        xLabel6.setExpression("#{entity.surveytype}");
        xLabel6.setOpaque(true);
        xLabel6.setPreferredSize(new java.awt.Dimension(300, 16));
        xFormPanel2.add(xLabel6);

        xLabel4.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel4.setCaption("Petsa sa Pagpangutana");
        xLabel4.setExpression("#{entity.surveydate}");
        xLabel4.setFor("");
        xLabel4.setOpaque(true);
        xLabel4.setPreferredSize(new java.awt.Dimension(300, 16));
        xFormPanel2.add(xLabel4);

        xLabel7.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel7.setCaption("Petsa sa Pag-encode");
        xLabel7.setExpression("#{entity.recordlog.datecreated}");
        xLabel7.setFor("");
        xLabel7.setName(""); // NOI18N
        xLabel7.setOpaque(true);
        xLabel7.setPreferredSize(new java.awt.Dimension(300, 16));
        xFormPanel2.add(xLabel7);

        xLabel8.setBorder(new com.rameses.rcp.control.border.XLineBorder());
        xLabel8.setCaption("Gi-encode ni");
        xLabel8.setExpression("#{entity.recordlog.createdbyuser}");
        xLabel8.setFor("");
        xLabel8.setName(""); // NOI18N
        xLabel8.setOpaque(true);
        xLabel8.setPreferredSize(new java.awt.Dimension(300, 16));
        xFormPanel2.add(xLabel8);

        xHorizontalPanel1.add(xFormPanel2);

        add(xHorizontalPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XHorizontalPanel xHorizontalPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
}
