/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tagabukid.tagbalay.views.bak;


import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author rufino
 */
@Template({FormPage.class})
public class ModifyTagBalayGeneralInfoPage extends javax.swing.JPanel {

    /**
     * Creates new form EditDocumentGeneralInfoPage
     */
    public ModifyTagBalayGeneralInfoPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        entityLookup2 = new com.rameses.entity.components.EntityLookup();
        entityAddress2 = new com.rameses.enterprise.components.EntityAddress();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();

        xFormPanel1.setCaptionPadding(new java.awt.Insets(0, 5, 0, 5));
        xFormPanel1.setCaptionWidth(180);

        xIntegerField1.setCaption("Tile No.");
        xIntegerField1.setName("entity.tileno"); // NOI18N
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        xDateField2.setCaption("Petsa sa Pagpangutana");
        xDateField2.setName("entity.surveydate"); // NOI18N
        xDateField2.setRequired(true);
        xFormPanel1.add(xDateField2);

        xComboBox1.setAllowNull(false);
        xComboBox1.setCaption("Pangalan sa nag survey");
        xComboBox1.setExpression("#{item.name}");
        xComboBox1.setImmediate(true);
        xComboBox1.setIndex(-100);
        xComboBox1.setItems("surveyors");
        xComboBox1.setName("entity.survey.surveyor "); // NOI18N
        xComboBox1.setPreferredSize(new java.awt.Dimension(300, 20));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        entityLookup2.setCaption("Pangalan sa Pangulo sa Pamilya");
        entityLookup2.setExpression("#{entity.name}");
        entityLookup2.setName("entity.tagbalay.pangulo"); // NOI18N
        entityLookup2.setPreferredSize(new java.awt.Dimension(0, 21));
        entityLookup2.setRequired(true);
        xFormPanel1.add(entityLookup2);

        entityAddress2.setCaption("Nahimutangan sa Panimalay");
        entityAddress2.setName("entity.tagbalay.address"); // NOI18N
        entityAddress2.setPreferredSize(new java.awt.Dimension(0, 86));
        entityAddress2.setPropertyInfo(null);
        xFormPanel1.add(entityAddress2);

        xTextField1.setCaption("Mobile/Cellphone No.");
        xTextField1.setName("entity.mobileno"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(150, 20));
        xFormPanel1.add(xTextField1);

        xTextField2.setCaption("Phone No.");
        xTextField2.setName("entity.phoneno"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(150, 20));
        xFormPanel1.add(xTextField2);

        xTextField3.setCaption("Email Address");
        xTextField3.setName("entity.email"); // NOI18N
        xTextField3.setPreferredSize(new java.awt.Dimension(150, 20));
        xFormPanel1.add(xTextField3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.enterprise.components.EntityAddress entityAddress2;
    private com.rameses.entity.components.EntityLookup entityLookup2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
}
